### ISSUE TITLE
Module 'logger" not found

### ISSUE THREAD

**Issue by cosmincio** [zhouxichun/MMM-TiHimawari8Earth#1]
**Config.js**:

{
			module: 'MMM-TiHimawari8Earth',
			position: 'fullscreen_below',
			config: {}
		}

**Result**:

WARNING! Could not load config file. Starting with default configuration. Error found: Error: Cannot find module 'logger'
Require stack:
- /home/pi/MagicMirror/modules/MMM-TiHimawari8Earth/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js

[21.09.2023 12:36.57.625] [ERROR] Error: Cannot find module 'logger'
Require stack:
- /home/pi/MagicMirror/modules/MMM-TiHimawari8Earth/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-TiHimawari8Earth/node_helper.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10)
[21.09.2023 12:36.57.632] [ERROR] Whoops! There was an uncaught exception...
[21.09.2023 12:36.57.649] [ERROR] Error: Cannot find module 'logger'
Require stack:
- /home/pi/MagicMirror/modules/MMM-TiHimawari8Earth/node_helper.js
- /home/pi/MagicMirror/js/app.js
- /home/pi/MagicMirror/js/electron.js
- /home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:798:15)
    at Function../lib/common/reset-search-paths.ts.Module._resolveFilename (electron/js2c/browser_init.js:7718:16)
    at Function.Module._resolveFilename (/home/pi/MagicMirror/node_modules/module-alias/index.js:49:29)
    at Module._load (internal/modules/cjs/loader.js:691:27)
    at Function.Module._load (electron/js2c/asar.js:748:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/pi/MagicMirror/modules/MMM-TiHimawari8Earth/node_helper.js:1:13)
    at Module._compile (internal/modules/cjs/loader.js:968:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:986:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/pi/MagicMirror/modules/MMM-TiHimawari8Earth/node_helper.js',
    '/home/pi/MagicMirror/js/app.js',
    '/home/pi/MagicMirror/js/electron.js',
    '/home/pi/MagicMirror/node_modules/electron/dist/resources/default_app.asar/main.js',
    undefined
  ]
}

**Comment by zhouxichun** [comment]
Check your package.json file in Magicmirror's root.
Is there a "_moduleAliases" node  with an child entry "logger": "js/logger.js"?

**Comment by cosmincio** [comment]
'logger' entry is now present but there is another error. Cannot find module "fetch"

**Comment by zhouxichun** [comment]
fetch is a nodejs package. you should install it by:
npm install fetch --save.

Or you can simply download the latest version of MagicMirror. For me, it is 2.24.0.

**Comment by cosmincio** [comment]
done, thanks
