### ISSUE TITLE
[ERROR] TypeError: fetch is not a function

### ISSUE THREAD

**Issue by ghost** [zhouxichun/MMM-TiHimawari8Earth#2]
[2024-04-12 09:45:12.667] [INFO]  Newsfeed-Fetcher: Broadcasting 20 items.
[2024-04-12 09:45:12.684] [INFO]  updatenotification: Updater Class Loaded!
[2024-04-12 09:45:12.684] [INFO]  updatenotification: Checking PM2 using...
[2024-04-12 09:45:12.702] [INFO]  updatenotification: [PM2] You are not using pm2
[2024-04-12 09:45:12.779] [INFO]  MMM-TiHimawari8Earth: fetching data.
[2024-04-12 09:45:12.780] [ERROR] Whoops! There was an uncaught exception...
[2024-04-12 09:45:12.781] [ERROR] TypeError: fetch is not a function
    at Class.fetchData (C:\Users\Dias\Documents\smartmirror\MagicMirror\modules\MMM-TiHimawari8Earth\node_helper.js:45:5)
    at Timeout._onTimeout (C:\Users\Dias\Documents\smartmirror\MagicMirror\modules\MMM-TiHimawari8Earth\node_helper.js:29:14)
    at listOnTimeout (node:internal/timers:569:17)
    at process.processTimers (node:internal/timers:512:7)
[2024-04-12 09:45:12.782] [ERROR] MagicMirror² will not quit, but it might be a good idea to check why this happened. Maybe no internet connection?
[2024-04-12 09:45:12.782] [ERROR] If you think this really is an issue, please open an issue on GitHub: https://github.com/MagicMirrorOrg/MagicMirror/issues
[2024-04-12 09:45:13.373] [INFO]  Calendar-Fetcher: Broadcasting 372 events from https://calendar.google.com/calendar/ical/210103296%40stu.sdu.edu.kz/private-8a36224c994c4e8673f65736be03d003/basic.ics.
[2024-04-12 09:45:13.394] [INFO]  Calendar-Fetcher: Broadcasting 8 events from https://ics.calendarlabs.com/76/mm3137/KZ_Holidays.ics.
[2024-04-12 09:45:13.465] [INFO]  Newsfeed-Fetcher: reloadInterval set to ttl=3600000 for url https://rus.azattyq.org/api/zqmtvek-tt
[2024-04-12 09:45:13.520] [INFO]  Newsfeed-Fetcher: Broadcasting 20 items.

**Comment by zhouxichun** [comment]
fetch is a nodejs package. you should install it by:
npm install fetch --save.

Or you can simply download the latest version of MagicMirror. For me, it is 2.24.0.
